### ISSUE TITLE
[bpk-component-popover] Flow-types in npm module

### ISSUE THREAD

**Issue by ErlendS** [Skyscanner/backpack#1118]
Hi, I'm having trouble using `bpk-component-popover` because it ships with flowtypes in the .js files.

It would've been simple to strip them with a babel loader I guess, but in a TS project we do not have the option of using loaders. Is there any way you can bundle pure js files and move flow definitions to a separate file?

**Comment by arnaugm** [comment]
A project created with CRA also have problems with Flow in the dependencies. CRA provides support for Flow out of the box but for some reason it doesn't work with dependencies, any solutions for this?

**Comment by olliecurtis** [comment]
Hello 👋 

Its been a while but in the future we are exploring the possibility of shipping our components transpiled so this issue should hopefully disappear once this happens 😄 

Hope that helps

**Comment by olliecurtis** [comment]
Closing this as this has been some time but feel free to re-open if you have any further issues or concerns
