### ISSUE TITLE
BpkTextInput is broken after updating react-native to sdk 31

### ISSUE THREAD

**Issue by mathewthe2** [Skyscanner/backpack#1189]
BpkTextInput won't allow typing anything. Anything typed in will be overridden by blank.

react: 16.5.0
react-native: sdk 31

**Comment by shaundon** [comment]
Hi Matthew,

The text input requires you to manage its state yourself, see the React Native TextInput documentation here: https://facebook.github.io/react-native/docs/textinput (the `onChangeText` prop).

**Comment by mathewthe2** [comment]
I can assure you I have not changed anything in my implementation. It has been working when I was using sdk27. I can provide more environment information if needed.

**Comment by shaundon** [comment]
More environment information would be good, thanks. Do you have some sample code I can look at too? We can't really help you without more details and code.

**Comment by mathewthe2** [comment]
{
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "babel-preset-react-native": "^5.0.2",
    "jest-expo": "31.0.0",
    "react-native-bpk-component-button": "^7.1.1",
    "react-native-bpk-component-card": "^1.2.35",
    "react-native-bpk-component-flat-list": "^1.0.18",
    "react-native-bpk-component-horizontal-nav": "^3.0.23",
    "react-native-bpk-component-text": "^2.1.43",
    "react-native-bpk-component-text-input": "^3.0.6",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "rnpm": {
    "assets": [
      "./node_modules/bpk-svgs/dist/font"
    ]
  },
  "main": "./node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "deps": "^0.1.2",
    "expo": "^31.0.2",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-dom": "^16.6.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-bpk-component-icon": "^1.9.2",
    "react-native-calendar-select": "^0.1.2",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-device-info": "^0.22.2",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-modalbox": "^1.6.0",
    "react-native-nav": "^2.0.2",
    "socket.io-client": "^2.1.1"
  }
}

**Comment by shaundon** [comment]
Does it work if you use the built-in `TextInput` from React Native? The Backpack version largely uses the same props and just adds styling and validation so it should be easy to switch it out.

**Comment by mathewthe2** [comment]
TextInput in React Native works. How would I style the TextInput to look like the on in Backpack?

**Comment by shaundon** [comment]
Here's the styles we use: https://github.com/Skyscanner/backpack/blob/master/native/packages/react-native-bpk-component-text-input/src/styles.js

If you send over the actual code you're using I can try and replicate the issue and figure out what's wrong, but I can't help you any more without that.
