### ISSUE TITLE
Caret inside datepicker after selecting a date

### ISSUE THREAD

**Issue by mii9000** [Skyscanner/backpack#1399]
![datepicker](https://user-images.githubusercontent.com/6401874/56021464-af766d00-5d33-11e9-93dc-5ee6d1e849ae.png)
After selecting a date, a caret appears in the datepicker even though its not editable. IMO, either it should be made editable to reason about the caret appearing or if its to remain readonly then caret should not be visible at least.

**Comment by olliecurtis** [comment]
Hi 

Thanks for your message, we are reviewing our calendar component and this is something we are discussing and looking into as part of this.

Thanks
