### ISSUE TITLE
Outdated react-scripts

### ISSUE THREAD

**Issue by LaszloDev** [Skyscanner/backpack#1635]
Im checking Backpack out right now, to integrate in our project as component library.

The documentation says that `react-scripts` are forked to modify the webpack build script. 
[Using backpack-react-scripts](https://backpack.github.io/using/backpack-react-scripts)

Looking closer at the [`backpack-react-script`](https://github.com/Skyscanner/backpack-react-scripts) the repo was not updated in 9 months. Did just now find a guide on the `fork`-branch how to update, which does not look like a good process. [Update Guide](https://github.com/Skyscanner/backpack-react-scripts/tree/fork/packages/react-scripts)

[react-app-rewired](https://github.com/timarney/react-app-rewired) does enable you to change the CRA defaults and might be a better ways, as Im able to relay directly on the `react-scripts` and are able to update them easily.

Could you extend the documentation do clarify how to integrate Backpack within an existing app without using your `backpack-react-scripts?

Thanks a lot!

**Comment by georgegillams** [comment]
Hey 👋 
Unfortunately we only fully support using our components through backpack-react-scripts for now as we don't currently transpile JS/SCSS before publishing. It is possible to use them without BRS, but you would need to manually update your webpack config to process the files correctly. If you wanted to do that, you could take inspiration from the webpack config here:
https://github.com/Skyscanner/backpack/blob/master/.storybook/webpack.config.js

**Comment by ojcurtis** [comment]
Hello @LaszloDev 

Sorry for the delay in responding the team here have been very busy recently. Yes we have forked CRA as there is specific things we needed that CRA didn't give us the ability to at the time and things we needed internally, we are looking to upgrade BRS soon to bring it into alignment with the latest version.

Thanks for the suggestion of `react-app-rewired` we will check this out and check if it meets the requirements 😄 

The suggestion above should hopefully solve the problem of not using BRS

Thanks!
