### ISSUE TITLE
[bpk-component-datepicker] /bpk-component-calendar/src/BpkCalendarContainer.js: Support for the experimental syntax 'classProperties' isn't currently enabled (102:21)

### ISSUE THREAD

**Issue by aminmc** [Skyscanner/backpack#1961]
Hi 
Im trying to use the date picker component in my react app (created using CRA) and I'm getting the following:

```
 .../bpk-component-calendar/src/BpkCalendarContainer.js: Support for the experimental syntax 'classProperties' isn't currently enabled (102:21):

  100 |     }
  101 | 
> 102 |     handleDateFocus = (event, { date, source }) => {
      |                     ^
  103 |       const { onMonthChange } = this.props;
  104 |       const focusedDate = dateToBoundaries(
  105 |         date,

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

I've added the following to my package.json

```json
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties"
    ]
  },
```

but still getting the same error.  Am I missing something?

Thanks

**Comment by olliecurtis** [comment]
Hello @aminmc 

Currently our library does not work out of the box with vanilla CRA, as we do not ship our components transpiled - for this to work we have a fork of CRA called [Backpack React Scripts](https://github.com/Skyscanner/backpack-react-scripts) which has specific workings for building Backpack components as part of the build process.

We are hoping that in the future when we move to shipping our packages transpiled this will work OOTB with CRA and won't cause issues 😄 

Hope this helps, any questions let me know
