### ISSUE TITLE
[bpk-component-horizontal-nav]/[bpk-mixins] using incompatible shadow styles for React Native 

### ISSUE THREAD

**Issue by joeyfigaro** [Skyscanner/backpack#1974]
I started to dive into adding support for transforming scss files in my project and have managed to get the imports in your styles working properly with the following transformer/metro config:

```js
// sass-transformer.js
const upstreamTransformer = require('metro-react-native-babel-transformer')
const path = require('path')
const sassTransformer = require('react-native-sass-transformer')
const packageImporter = require('node-sass-package-importer')

const rootPath = path.resolve(__dirname, '../..')
const modulesPath = path.resolve(rootPath, 'node_modules')

module.exports.transform = function({ src, filename, options }) {
  if (filename.endsWith('.scss') || filename.endsWith('.sass')) {
    const opts = Object.assign(options, {
      sassOptions: {
        importer: [
          packageImporter({
            cwd: rootPath,
            packagePrefix: '~'
          })
        ]
      }
    })

    return sassTransformer.transform({ src, filename, options: opts })
  } else {
    return upstreamTransformer.transform({ src, filename, options })
  }
}
```

```js
// metro.config.js
const path = require('path')
const { sourceExts } = require('metro-config/src/defaults/defaults')
const reactNativePath = require.resolve('react-native')

const reactNativeFolder = `${
  reactNativePath.split('node_modules/react-native/')[0]
}node_modules/react-native/`

module.exports = {
  watchFolders: [path.resolve(__dirname, '../../'), path.resolve(__dirname)],
  transformer: {
    babelTransformerPath: require.resolve('./sass-transformer'),
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false
      }
    })
  },
  resolver: {
    sourceExts: [...sourceExts, 'scss', 'sass']
  }
}
```

But now, it fails when trying to parse the (what I assume are) base shadows specified in `bpk-mixins` with the following:

> bpk-component-horizontal-nav/src/BpkHorizontalNav.scss: Failed to parse declaration "boxShadow: 0 1px 0 0 #dddde5"

It looks like this is because [React Native does not support the spread radius parameter](https://github.com/kristerkari/react-native-postcss-transformer/issues/3). 

Is the shadows partial supposed to be used when the consuming project is built with React Native?

**Comment by joeyfigaro** [comment]
Whoops! Just discovered there's [backpack-react-native](https://github.com/Skyscanner/backpack-react-native)—I'm assuming starting over using that instead of individual component packages is the route I need to take. You guys should consider adding a note about this in your docs. ⭐ 

Do you accept PRs? I'd be happy to propose the changes.

**Comment by olliecurtis** [comment]
Hey @joeyfigaro - Yes `backpack-react-native` is the place to be as this repo is mainly for the web version of our components and not compatible with RN.

We can certainly look at adding that - this is probably something we missed when we split all our platforms out to individual repos instead of one large monorepo.

We do also link to the different codebases from our docs site https://backpack.github.io - which if you have not checked out yet has guidance and information about all our different DS elements and platforms we support.

Thanks

**Comment by olliecurtis** [comment]
Just had a check and we do have this re-direct link to our RN repo but maybe we need to look at surfacing it better for our users 😄 

https://github.com/Skyscanner/backpack/tree/master/native
