### ISSUE TITLE
No bpk-component-switch in the readme?

### ISSUE THREAD

**Issue by w0rmr1d3r** [Skyscanner/backpack#2399]
Hello!

It seems this package:
https://backpack.github.io/components/switch?platform=web
https://www.npmjs.com/package/bpk-component-switch

Does not appear in the readme file, has it been deprecated?

Thanks!

**Comment by olliecurtis** [comment]
Hey @w0rmr1d3r you are right it is missing! Looks to be a small blip and the component is still active and supported. 

Seems when we created the component we missed it from the README!

Will get that updated now!

Thanks for flagging
Ollie

**Comment by olliecurtis** [comment]
Hello, 

This issue has now been resolved and the package file updated so will close this issue!

Thanks again for raising
Ollie
