### ISSUE TITLE
Error while installing calendar component

### ISSUE THREAD

**Issue by SaaeedK** [Skyscanner/backpack#2510]
getting following error when trying to install calendar component from backpack

![image](https://user-images.githubusercontent.com/75593735/181129130-b5acd5cb-9b7a-462d-93e2-bf3449d9d194.png)

**Comment by olliecurtis** [comment]
Hello @SaaeedK 👋

From the error you have shared this is expected as currently Backpack components are not compatible with React 18 and only at the moment 16 & 17.

We will be in the future looking to support 18 when our business is ready for it, but for now it's only compatible on lower versions.

Sorry about that and hope that helps 🙂
@olliecurtis
