### ISSUE TITLE
[feature request] Add holiday highlight in bpk-calendar

### ISSUE THREAD

**Issue by imrickywong** [Skyscanner/backpack#2694]
Hi there, thanks for sharing such a great UI component.

I suppose one key point for  people deciding when to  travel  is the holiday, so what about giving the  highlight of public holidays when our customers come through our monthly prices calendar
of flights or hotels, which would reduce the cost of checking whether they will be free or not.

I started doing some research on the source code, and it turns out that `packages/bpk-component-calendar/src/BpkCalendarDate.js` is related.  

Is this feature useful or in the roadmap? I'd like to contribute and make a little progress on this amazing project.

Please let me know if that sounds ok.

**Comment by olliecurtis** [comment]
Hi Ricky

Thanks for the suggestion and improvement. Currently it's not something on our roadmap as a feature as it's not a requirement we currently have as a company but it is possible to provide the functionality yourself by passing a custom `BpkCalendarDate` to the component using the `composeCalendar` HOC.

You can customize many parts of the calendar via this HOC too so can go beyond the out of the box experience to really make it your own 😄

Hope this helps
Ollie

**Comment by imrickywong** [comment]
got it, thanks 😄
