### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by vr1Ravi** [Skyscanner/backpack#3001]
Module C:/Users/rajku/OneDrive/Desktop/Enhance/skyProject/node_modules/@skyscanner/backpack-web/bpk-component-button/themeAttributes.js:17 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@skyscanner/backpack-web" asking them to ship the file 
in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

**Comment by olliecurtis** [comment]
Hey @vr1Ravi Out of interest how is it that you are using the Backpack Web package? Do you have a sample project that you could link to see more about this issue?

Only reason to ask is this is the first time we have seen such issue as within Skyscanner we use this package in multiple places, so would be good to understand the environment you are using to be assist with investigation.

All the best

**Comment by olliecurtis** [comment]
Hey we have made some changes to how we transpile our Backpack package which should hopefully now solve this issue. Closing as no response in a while but feel free to reopen it if you still face issues.

Thanks
