### ISSUE TITLE
Mini StackBlitz (or similar) demo request

### ISSUE THREAD

**Issue by alex-schernbeck** [Skyscanner/backpack#3068]
Dear Skyscanner Team,

I love your Backback design system and would like to understand how your components work.

As I am unfortunately pretty new to React, I would need a little bit help from your side.

Could you provide a mini-example e.g. for the **Graphic promotion** (or other) on e.g. **StackBlitz** (or similar), how the component has to be integrated cocretely in the simplest possible case (like a minimum setup)?

Unfortunately I was not able to figure out with your "Usage" example at https://www.skyscanner.design/latest/components/graphic-promotion/web-0qnj8MN6#section-props-e3 how to achieve this.

Perhaps you could spare 5 minutes to provide a small example, as can be found on the official React website, for example.

That would be great and a big help!

Thanks a lot in advance!

Best regards
Alex

**Comment by alex-schernbeck** [comment]
Hi Ollie,

Thank you very much for your quick reply and help! Unfortunately I was ill, so I can only reply today.

I tried to execute your instructions, but the script unfortunately aborts with the following error:
9277 error gyp ERR! find VS 
9277 error gyp ERR! find VS msvs_version not set from command line or npm config
9277 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
9277 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
9277 error gyp ERR! find VS looking for Visual Studio 2015
9277 error gyp ERR! find VS - not found
9277 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
9277 error gyp ERR! find VS 
9277 error gyp ERR! find VS **************************************************************
9277 error gyp ERR! find VS You need to install the latest version of Visual Studio
9277 error gyp ERR! find VS including the "Desktop development with C++" workload.
9277 error gyp ERR! find VS For more information consult the documentation at:
9277 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
9277 error gyp ERR! find VS **************************************************************
9277 error gyp ERR! find VS 
9277 error gyp ERR! configure error 
9277 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
9277 error gyp ERR! stack     at VisualStudioFinder.fail (C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
9277 error gyp ERR! stack     at C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\find-visualstudio.js:75:16
9277 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
9277 error gyp ERR! stack     at C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\find-visualstudio.js:71:14
9277 error gyp ERR! stack     at C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\find-visualstudio.js:384:16
9277 error gyp ERR! stack     at C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\util.js:54:7
9277 error gyp ERR! stack     at C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-gyp\lib\util.js:33:16
9277 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
9277 error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
9277 error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
9277 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
9277 error gyp ERR! System Windows_NT 10.0.19045
9277 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\MAMP\\htdocs\\{{TESTPROJECT}}\\SANDBOX\\SKYSCANNER\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
9277 error gyp ERR! cwd C:\MAMP\htdocs\{{TESTPROJECT}}\SANDBOX\SKYSCANNER\my-app\node_modules\node-sass
9277 error gyp ERR! node -v v20.9.0
9277 error gyp ERR! node-gyp -v v8.4.1
9277 error gyp ERR! not ok 
9277 error Build failed with error code: 1
9278 verbose exit 1
9279 timing npm Completed in 111502ms
9280 verbose unfinished npm timer reify 1699957725456
9281 verbose unfinished npm timer reify:build 1699957796544
9282 verbose unfinished npm timer build 1699957796552
9283 verbose unfinished npm timer build:deps 1699957796554
9284 verbose unfinished npm timer build:run:postinstall 1699957804096
9285 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1699957804585
9286 verbose code 1
9287 error A complete log of this run can be found in: C:\Users\{{USERNAME}}\AppData\Local\npm-cache\_logs\2023-11-14T10_28_44_994Z-debug-0.log

I have used the following versions and tools:
VS Code
Version: 1.84.0 (user setup)
$ nvm -v
1.1.11
$ node -v
v20.9.0
$ npm -v
10.1.0
$ python --version
Python 3.12.0

Do you know where the error could be?

Many thanks in advance!

Thanks
Alex

**Comment by alex-schernbeck** [comment]
Hi @olliecurtis,

Would you or one of your team members have a moment to look at the errors?

Thanks in advance!

BR
Alex

**Comment by olliecurtis** [comment]
Hey @alex-schernbeck 

Sorry for the delay, looking at that error it's not something we are familiar with seeing with the VSCode error.

I do notice that your python version is up on the latest, would you be able to downgrade to 3.9 and give it a try? As I know that node-gyp bundled with node-sass isn't happy on newer versions.

It's worth noting too I noticed you look to be developing on windows which can also be an issue with tooling compatibility too, unfortunately our support is limited when it comes to Windows as we don't develop on this platform and use MacOS for development here so support is limited/untested

Let me know how that goes
Ollie

**Comment by olliecurtis** [comment]
It might also be worth bumping down your node version too to test and this is our current aligned version of 18 as per our docs, so it could be that Node is playing a factor here with node-sass compatibility

Something we are working on removing out of Backpack too!

**Comment by olliecurtis** [comment]
Stale: Closing due to no updates
