### ISSUE TITLE
Extract the in Web UI price of individual fligths when there's 1 or multiple stops

### ISSUE THREAD

**Issue by Ethanol48** [Skyscanner/backpack#3158]
This is not an issue with the code, but I can't find anywhere else to comment on this.

I'm trying to build an addon or extension for browsers that will give you a more realistic price for a determined demographic.

For residents of the Canary Islands if they make a travel inside Spain they have a 75% discount if they depart from the Canary Islands or go to the Canary Islands. 

This means that the website doesn't give the real price and the 'best price' isn't accurate.

I was wondering if is there a way to extract in the web UI without the need for an API call.

**Comment by olliecurtis** [comment]
Hey @Ethanol48 

Sorry this isn't something we will be able to help here with. If you have a Skyscanner request I can point you towards our helpsite where you can raise a request and get support through there: https://help.skyscanner.net/hc/en-gb/requests/new?skyArticle=201001141 

Thanks

**Comment by olliecurtis** [comment]
Closing as resolution is to contact Skyscanner
