### ISSUE TITLE
[Docs] In page anchor links require two clicks to scroll to anchor

### ISSUE THREAD

**Issue by rik** [Skyscanner/backpack#390]
## Steps to reproduce
1. Go to https://backpack.github.io/components/web/badge/
2. Click on 'Visually centered' anchor link

## Actual
Document location includes the anchor but the document does not scroll. Clicking a second time on the same anchor link will scroll to the anchor.

## Expected
First click scrolls to the anchor. (And document location still includes the anchor)

## Notes
I suspect the router to interfere and do something like `e.preventDefault()`. I've only looked at it with minified code so haven't done a real debugging session.

**Comment by georgegillams** [comment]
This is due to the line `onUpdate: () => window.scrollTo(0, 0)`in `bpk-docs/src/index.js`
When an anchor is clicked the URL is updated, causing it to scroll back to `(0, 0)`

**Comment by georgegillams** [comment]
This is now fixed, and will be live in a few minutes. Thanks again @rik for reporting the issue!
