### ISSUE TITLE
Country flag after changing currency

### ISSUE THREAD

**Issue by jdreyesp** [Skyscanner/backpack#479]
The country flag doesn't change after submitting a country / currency change in the flights result page.

PS: Don't know if this repo is the correct one, please forward it to the correct one if this is not correct.

**Comment by matthewdavidson** [comment]
Hi @jdreyesp! Thanks for raising this, you are right in suggesting that this might not be the correct repo to raise. I've forwarded this onto the relevant internal issues tracking tool and made a not of the email on your GH profile incase there is any follow up required! Thanks!
