### ISSUE TITLE
Module not found after last release

### ISSUE THREAD

**Issue by alex-ju** [Skyscanner/backpack#55]
Running
```
npm install -g create-react-app

create-react-app my-app --scripts-version=backpack-react-scripts
cd my-app
npm start
```
returns the following error
```
Failed to compile.

./~/bpk-react-utils/src/withDefaultProps.js
Module not found: Can't resolve 'recompose/wrapDisplayName' in '~/my-app/node_modules/bpk-react-utils/src'
```

This is happening after today's new release, previous release worked just fine.

**Comment by k0nserv** [comment]
Hey @alex-ju,

Yeah this was an error introduced with the release I did earlier today. Fix is merged in https://github.com/Skyscanner/backpack/pull/54 and should be released shortly

**Comment by k0nserv** [comment]
That's it released with https://github.com/Skyscanner/backpack/commit/1b02e67ee36227e46753af779d63075a13f0fef2. Please give us a shout if that doesn't fix the problem

**Comment by alex-ju** [comment]
Yep, #54 fixed it.
Keep up the good work!
