### ISSUE TITLE
Calendar focus incorrectly tracked when using mouse and keyboard

### ISSUE THREAD

**Issue by edwardhorsford** [Skyscanner/backpack#58]
It's possible to get in to an edge case where the calendar component thinks the focus / active date is in a different position to where it actually is.

See video:
![skyscanner-date-picker-focus-bug](https://user-images.githubusercontent.com/2204224/29615948-a168e830-8807-11e7-94b4-cc89bba7d595.gif)

Steps to reproduce:
* Select / focus a date.
* Use mouse to focus another date, click dragging off it so that it doesn't select.
* Confirm visual focus is on a new date
* Use arrow keys to move to a new date - it will move from where the first date was, not where the current focus is.

Tested on Chrome 60.0.3112 on OSX

**Comment by k0nserv** [comment]
Thanks for the report @edwardhorsford, we'll have a look at this

**Comment by tvooo** [comment]
Oooh, very good catch :) So, focus here is set through the native browser events, but apparently the onClick handler on the date does not fire (which would set the ring outline / state correctly). Worth investigating if we should move that to `onMouseDown` instead.

**Comment by georgegillams** [comment]
Looking for some feedback here - As you know the current behaviour is as follows:
![now](https://user-images.githubusercontent.com/30267516/30021531-96b1fef2-915f-11e7-9299-c8a70dd1bd34.gif)

By hooking up to the `onFocus` event on each button we can ensure that browser focus and our focus are always the same. This produces the following behaviour, but there's a catch - when you click on a value outside the current month, the focus event causes the month to change, meaning that the click event is never handled (unless you click really quickly)
![simple_fix](https://user-images.githubusercontent.com/30267516/30021620-e1251ec4-915f-11e7-8f5e-474bfd3fdb15.gif)

The last solution I have to offer is implemented here:
https://github.com/Skyscanner/backpack/pull/71/files
It produces the following behaviour which is arguably the most correct, but it involves mouse event listeners, state and a whole load of work for our component - and just feels wrong!
![involved_fix](https://user-images.githubusercontent.com/30267516/30021663-0a567c52-9160-11e7-86fc-b6c337d0a358.gif)

**Comment by edwardhorsford** [comment]
Hello! Thanks for looking at this.

From my point of view, either solution looks good. The main thing is that real focus and 'calendar' focus stay in sync - it looks like both do this.

**Comment by jamesf3rguson** [comment]
Unfortunately, we don't have plans to enable support for this at the moment. Accessibility is an important factor of every Backpack component and we'll continue to review support going forward. We always welcome PRs should this be something you require to be able to use this component.
