### ISSUE TITLE
Bpk-modal requires id but can't see it in usage section 

### ISSUE THREAD

**Issue by realYukiko** [Skyscanner/backpack#605]
Hi, according to https://backpack.github.io/components/web/modals, `id` in props is a required field, however,  in the usage section of the doc, it doesn't pass `id` to the component. 

Besides, may I ask how `id` works on modal component? looks like it is only used in `aria-labelledby`?

**Comment by k0nserv** [comment]
Hey @realYukiko you're right it is missing and it's used for `aria-labelledby ` priamrily
