### ISSUE TITLE
Calendar may not be usable if users are using custom colours

### ISSUE THREAD

**Issue by edwardhorsford** [Skyscanner/backpack#63]
There's a few bugs with the calendar (and possibly other components) if users are using custom colours. I don't know how much you want to make these work for various accessibility needs, but you can generally get to a point where text doesn't disappear without much work. The point isn't generally to make the interface perfect, but to avoid entire elements disappearing.

Different issues occur depending on if you're using a dark or light background. Examples of each:

## Light background:
![screen shot 2017-08-24 at 16 23 21](https://user-images.githubusercontent.com/2204224/29674101-0dd81ba8-88e9-11e7-862c-f348d0a47b7d.png)
In this screenshot, the 25th is the selected month - this isn't clear as only the bolding is shown, not the solid dot.

## Dark background:
![screen shot 2017-08-24 at 16 24 33](https://user-images.githubusercontent.com/2204224/29674155-2f6bd6f6-88e9-11e7-8c4f-6b3147a0799f.png)

In this screenshot, none of the text or selected months are visible.

If you'd like more information on using custom colours, we [wrote a blog](https://accessibility.blog.gov.uk/2017/03/27/how-users-change-colours-on-websites/) about how we fixed our buttons when used with custom colours.

You might also find [Marian Foley's blog on how she uses custom colours](https://accessibility.blog.gov.uk/2016/05/26/accessibility-and-me-marian-foley/) interesting.

Let me know if you'd like any more information.

**Comment by jamesf3rguson** [comment]
Unfortunately, we don't have plans to enable support for this at the moment. Accessibility is an important factor of every Backpack component and we'll continue to review support going forward. We always welcome PRs should this be something you require to be able to use this component.
