### ISSUE TITLE
Bpk-component-modal flickers when tapping background

### ISSUE THREAD

**Issue by martrik** [Skyscanner/backpack#645]
Hello!

We're experiencing an issue with `bpk-component-modal` on iOS devices. When the modal is open, tapping on its background causes it to flicker (see zipped video). The modals in https://backpack.github.io/components/web/modals also exhibit this problem on iOS.

[Modal tap Flicker.mov.zip](https://github.com/Skyscanner/backpack/files/1883567/Modal.tap.Flicker.mov.zip)

**Comment by k0nserv** [comment]
Fixed in #770
