### ISSUE TITLE
bpk-component-icon. Failed to compile.

### ISSUE THREAD

**Issue by johnunclesam** [Skyscanner/backpack#654]
I'm using `create-react-app` latest, default.

I'm trying to use basic `Icon` component but I have this:

```log
Failed to compile.

./node_modules/bpk-component-icon/sm/chevron-down.js
Module parse failed: Unexpected token (10:9)
You may need an appropriate loader to handle this file type.
|       props = _objectWithoutProperties(_ref, ["styles"]);
|
|   return <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18" style={{
|     width: "1.125rem",
|     height: "1.125rem"
```

**Comment by johnunclesam** [comment]
https://github.com/facebook/create-react-app/issues/3663

**Comment by johnunclesam** [comment]
https://github.com/gorangajic/react-icons/pull/125

**Comment by matthewdavidson** [comment]
Hey there @johnunclesam! Thanks for trying out our design system. 

Backpack components are not compatible with Facebook's `create-react-app` out of the box as they are published to npm uncompiled, this is documented [on our docs site](https://backpack.github.io/using/getting-started#react-components).

Not to fret, we have a forked version called `backpack-react-scripts` which,  amongst other things, has the ability to compile backpack components! Checkout out it's [documentation](https://backpack.github.io/using/backpack-react-scripts).

Hope this helps.

**Comment by johnunclesam** [comment]
We cannot use on an existing project `--scripts-version=backpack-react-scripts`. This is very bad.

Is there another way? Is there a way to achive those components already compiled?

If not we cannot use and enojy your amazing works!

**Comment by matthewdavidson** [comment]
@johnunclesam unfortunately there is no other straightforward method of using Backpack components inside a `create-react-app` project - you'd have to [eject](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject) and modify the webpack configuration to compile Backpack components (this is what our custom fork achieves).

**Comment by johnunclesam** [comment]
And with something like this: https://github.com/timarney/react-app-rewired, without ejecting?

And what if you compile components aside uncompiled components?
