### ISSUE TITLE
backpack does not seem to be jest unit-test friendly.

### ISSUE THREAD

**Issue by MaxGoh** [Skyscanner/backpack#752]
It seems like the component packages are not being transpiled into ES5, and I can't seem to ignore them either, which renders me unable to do any unit testing on any components.

Could this be something that I'm doing wrong or backpack's issue?

I have tried testing with different starterkit

`create-react-app my-app --scripts-version=backpack-react-scripts`
`create-react-app`

I'm getting error message of

`"Syntax Error: 'import' ....'`

**Comment by shaundon** [comment]
Handled in another avenue of communication.
