### ISSUE TITLE
Replace .css file imports with .scss files

### ISSUE THREAD

**Issue by fklein-lu** [Skyscanner/backpack#833]
Importing `.css` files has been deprecated in newer versions of Node LibSass.

Renaming the `.css` files with `.scss` should fix this, and remove the deprecation warning without any side effects.

**Comment by matthewdavidson** [comment]
Hey @fklein-lu! Thanks for this - the only instance I am aware of once instance of this:
https://github.com/Skyscanner/backpack/blob/master/packages/bpk-stylesheets/index.scss#L19

Is this what you are referring to?

**Comment by fklein-lu** [comment]
Yes, this seems to be the only occurrence.

**Comment by spacedmonkey** [comment]
@fklein-lu Is there a fix this incoming? I get this message on every build

**Comment by spacedmonkey** [comment]
More information can be found on this issue here - https://github.com/sass/node-sass/issues/2362

**Comment by tiagoengel** [comment]
Hey @spacedmonkey we didn't really have a solution for this. The warning has been reverted in libsass@3.5.5 but the latest node-sass is using 3.5.4. It should eventually land on node-sass and remove this warning. 

On top of that we will be actually changing all backpack components to import pre compiled css files in the neat future, which should also get rid of this warning.

**Comment by spacedmonkey** [comment]
A better solution here would be not use css at all. How about using something like [normalize-scss](https://www.npmjs.com/package/normalize-scss), which is a port of normalize.css to scss.

**Comment by tiagoengel** [comment]
I'd say considering this is just a warning, that has been removed in the next version and considering we plan to ship only css files in the future, there is no need to do this right now.

We shipping pre compiled css files is to reduce the build time, it has nothing to do it this but it will also remove this warning.
